name: my_personal_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  form_field_validator: 1.1.0
  flutter_svg: 1.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/logo/
  uses-material-design: true

fonts: 
  - family: Plus Jakarta
    fonts: 
      - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Regular.otf
      - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Medium.otf
        weight: 500
      - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Bold.otf
        weight: 700
  - family: Grandis Extended
    fonts: 
      - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
      - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
        weight: 300
      - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
        weight: 500
      - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
        weight: 700
      - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
        weight: 900

